name: Rust CI

on:
  push:
    branches: [ "master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
     
      - name: Cargo Check
        run: cargo check
      
      - name: Check Formatting
        run: cargo fmr --all -- --check
      
      - name: Clippy
        run: cargo clippy -- -D warnings
      
      - name: Documentation
        run: cargo doc --no-deps
